#pragma once
#ifndef GEAR_RETURN_CODE
#define GEAR_RETURN_CODE

enum gear_status_t {
	GEAR_STATUS_SUCCESS,
	GEAR_STATUS_NO_ACTION,
	GEAR_STATUS_INDEFINITE_ACTION,
	GEAR_STATUS_MISSING_FILE_PATH,
	GEAR_STATUS_FAILED_TO_OPEN_FILE,
	GEAR_STATUS_FAILED_TO_READ_FILE,
	GEAR_STATUS_FAILED_TO_ALLOCATE_MEMORY,
	GEAR_STATUS_MISSING_PREPROCESSOR_DIRECTIVE,
	GEAR_STATUS_UNKNOWN_PREPROCESSOR_DIRECTIVE,
};

typedef long signed int gear_status_t;

#endif