#pragma once
#ifndef GEAR_RETURN_CODE
#define GEAR_RETURN_CODE

#include "gear-typedefs.h"

typedef ptrdiff_t gstatus_t;
enum {
	GEAR_STATUS_SUCCESS,
	GEAR_STATUS_NO_ACTION,
	GEAR_STATUS_UNKNOWN_ACTION,
	GEAR_STATUS_MISSING_FILE_PATH,
	GEAR_STATUS_FAILED_TO_OPEN_FILE,
	GEAR_STATUS_FAILED_TO_READ_FILE,
	GEAR_STATUS_FAILED_TO_ALLOCATE_MEMORY,
	GEAR_STATUS_FAILED_TO_PREPROCESS,
	GEAR_STATUS_UNRESOLVED_EXPRESSION,
	GEAR_STATUS_MISSING_PREPROCESSOR_DIRECTIVE,
	GEAR_STATUS_UNKNOWN_PREPROCESSOR_DIRECTIVE,
	GEAR_STATUS_MISSING_EXPRESSION,
};

extern const char* GearStatusStrings[];
extern const size_t GearStatusStringsCount;

#endif