#include <gear-grammar.h>

const char* GearGrammarGroupStrings[] = {
	"undefined",
	"redundant",
	"operator",
	"numeric literal",
	"string literal"
};

const gtoken_t GearGrammar[] = {
	{ GEAR_GRAMMAR_GROUP_REDUNDANT, GEAR_GRAMMAR_TYPE_SINGLE_LINE_COMMENT, "1//" },
	{ GEAR_GRAMMAR_GROUP_REDUNDANT, GEAR_GRAMMAR_TYPE_MULTILINE_COMMENT, "1/*0*/" },
	{ GEAR_GRAMMAR_GROUP_STRING_LITERAL, GEAR_GRAMMAR_TYPE_CHAR_LITERAL, "1\'0\\" },
	{ GEAR_GRAMMAR_GROUP_STRING_LITERAL, GEAR_GRAMMAR_TYPE_STRING_LITERAL, "1\"0\\" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_LSH_AND_ASSIGN, "<<=" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_RSH_AND_ASSIGN, ">>=" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_EQUAL_TO, "==" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_NOT_EQUAL, "!=" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_GREATER_OR_EQUAL, ">=" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_LESS_OR_EQUAL, "<=" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_LSH, "<<" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_RSH, ">>" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_INC, "++" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_DEC, "--" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_ADD_AND_ASSIGN, "+=" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_SUB_AND_ASSIGN, "-=" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_MUL_AND_ASSIGN, "*=" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_DIV_AND_ASSIGN, "/=" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_MOD_AND_ASSIGN, "%=" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_AND_AND_ASSIGN, "&=" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_OR_AND_ASSIGN, "|=" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_XOR_AND_ASSIGN, "^=" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_ADD, "+" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_SUB, "-" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_MUL, "*" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_DIV, "/" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_MOD, "%" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_GREATER_THAN, ">" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_LESS_THAN, "<" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_NOT, "!" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_AND, "&" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_OR, "|" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_XOR, "^" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_COMPLEMENT, "~" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_ASSIGN, "=" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_OPENING_PARENTHESIS, "(" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_CLOSING_PARENTHESIS, ")" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_OPENING_BRACKET, "[" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_CLOSING_BRACKET, "]" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_OPENING_BRACE, "{" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_CLOSING_BRACE, "}" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_PREPROCESSOR_DIRECTIVE, "@" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_DOT, "." },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_COMMA, "," },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_COLON, ":" },
	{ GEAR_GRAMMAR_GROUP_OPERATOR, GEAR_GRAMMAR_TYPE_OPERATOR_SEMICOLON, ";" }
};

const size_t GearGrammarCount = sizeof(GearGrammar) / sizeof(GearGrammar[0]);

size_t gfind_grammar_index_by_type(size_t type) {
	for (size_t i = 0; i < GearGrammarCount; i++) if (GearGrammar[i].type == type) return i;
	return NPOS;
}